server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: presentationService
          uri: http://localhost:8092/export/
          predicates:
            - Path= /export/**


zipkin:
    base-url: http://localhost:9411/zipkin/

management:
  tracing:
    sampling:
      probability: 1.0
