logging:
  file:
    path: C:/Users/615639/Desktop/logs/apigateway
  root: INFO
  org:
    springframework:
      boot:
        logging:
          LogLevel: INFO

server:
  port: 8080
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: presentationService
          uri: http://localhost:8092/export/
          predicates:
            - Path= /export/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/