logging:
  file:
    path: C:/Users/615639/Desktop/logs/eureka
  root: INFO
  org:
    springframework:
      boot:
        logging:
          LogLevel: INFO

server:
  port: 8761
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0
  instance:
    hostname: localhost
