greeting: Hello from input service

spring:
  application:
    name: input-service
  cloud:
    config:
      uri: http://localhost:8088

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/ , http://localhost:9001/eureka/
    registry-fetch-interval-seconds: 1