server:
  port: 8088
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: true

zipkin:
  base-url: http://localhost:9411/
management:
  tracing:
    sampling:
      probability: 1.0