server:
  port: 8088

spring:
  application:
    name: ConfigService
  profiles:
    active: native
  cloud:
    config:
      server:
        bootstrap: true

zipkin:
  base-url: http://localhost:9411/zipkin/
management:
  tracing:
    sampling:
      probability: 1.0