name: Maven Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Config service
        run: mvn -f configService/pom.xml clean install

      - name: Eureka
        run: mvn -f eureka/pom.xml clean install

      - name: Input Service
        run: mvn -f inputService/pom.xml clean install

      - name: Ripper Service
        run: mvn -f ripperService/pom.xml clean install

      - name: Presentation Service
        run: mvn -f presentationService/pom.xml clean install

      - name: Log Service
        run: mvn -f logService/pom.xml clean install
